In [75]:
import numpy as np
import pandas as pd


df = pd.read_csv("lab3.csv", sep=r"\s+")
print(df.columns.tolist())
df.head()


['BP', 'Cholesterol', 'Age', 'Pregnant', 'DrugReaction']


,BP,Cholesterol,Age,Pregnant,DrugReaction
0,100,150,20,0,0
1,120,160,16,0,0
2,110,150,18,0,0
3,100,175,25,0,0
4,95,250,36,0,0


In [91]:
X = df.drop("DrugReaction", axis=1)
y = df["DrugReaction"]
X = X.values
y = np.where(y == 0, -1, 1) # Convert 0 to -1 so labels are -1 and 1
y


array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [ ]:
# Normalize features
mu = X.mean(axis=0)
sigma = X.std(axis=0)
sigma[sigma == 0] = 1
X = (X - mu) / sigma
X

array([[-1.21685296, -1.2530773 , -0.96139715, -1.        ],
       [-0.32647274, -0.89573586, -1.17784679, -1.        ],
       [-0.77166285, -1.2530773 , -1.06962197, -1.        ],
       [-1.21685296, -0.35972371, -0.6908351 , -1.        ],
       [-1.43944801,  2.32033705, -0.09559859, -1.        ],
       [-0.77166285,  0.53362988,  0.9866496 , -1.        ],
       [-0.32647274, -0.18105299,  1.14898683, -1.        ],
       [ 1.00909757, -0.35972371,  0.3914131 , -1.        ],
       [ 1.45428768, -0.00238228,  0.12085105, -1.        ],
       [-0.10387769,  0.35495916, -0.96139715,  1.        ],
       [ 0.34131241,  0.17628844, -1.06962197,  1.        ],
       [ 1.67688273,  0.53362988, -0.6908351 ,  1.        ],
       [ 0.78650252, -0.35972371, -0.42027305,  1.        ],
       [-0.32647274, -0.18105299, -0.52849787,  1.        ],
       [-1.21685296, -0.18105299, -0.90728474,  1.        ],
       [-1.21685296, -0.89573586, -1.01550956,  1.        ],
       [-1.43944801,  2.

In [ ]:
# Add bias term (intercept)
X = np.concatenate([np.ones((X.shape[0], 1)), X], axis=1)
X

array([[ 1.        , -1.21685296, -1.2530773 , -0.96139715, -1.        ],
       [ 1.        , -0.32647274, -0.89573586, -1.17784679, -1.        ],
       [ 1.        , -0.77166285, -1.2530773 , -1.06962197, -1.        ],
       [ 1.        , -1.21685296, -0.35972371, -0.6908351 , -1.        ],
       [ 1.        , -1.43944801,  2.32033705, -0.09559859, -1.        ],
       [ 1.        , -0.77166285,  0.53362988,  0.9866496 , -1.        ],
       [ 1.        , -0.32647274, -0.18105299,  1.14898683, -1.        ],
       [ 1.        ,  1.00909757, -0.35972371,  0.3914131 , -1.        ],
       [ 1.        ,  1.45428768, -0.00238228,  0.12085105, -1.        ],
       [ 1.        , -0.10387769,  0.35495916, -0.96139715,  1.        ],
       [ 1.        ,  0.34131241,  0.17628844, -1.06962197,  1.        ],
       [ 1.        ,  1.67688273,  0.53362988, -0.6908351 ,  1.        ],
       [ 1.        ,  0.78650252, -0.35972371, -0.42027305,  1.        ],
       [ 1.        , -0.32647274, -0.1

In [ ]:
import numpy as np

# Sigmoid function
def sigmoid(s):
    return 1.0 / (1.0 + np.exp(-s))

# Shuffle and split data
np.random.seed(0)
N = X.shape[0]
idx = np.random.permutation(N)
Ntr = int(0.6 * N)
tr_idx, te_idx = idx[:Ntr], idx[Ntr:]

Xtr, ytr = X[tr_idx], y[tr_idx]
Xte, yte = X[te_idx], y[te_idx]

# Add bias term (column of ones)
Xtr_bias = np.hstack([np.ones((Xtr.shape[0], 1)), Xtr])
Xte_bias = np.hstack([np.ones((Xte.shape[0], 1)), Xte])

# Train logistic regression
def train_logistic(X, y, lr=0.1, n_iter=5000):
    n, d = X.shape
    w = np.zeros(d)
    for i in range(n_iter):
        p = sigmoid(X.dot(w))
        grad = X.T.dot(p - y) / n
        w -= lr * grad
    return w
# Train on training set
w = train_logistic(Xtr_bias, ytr, lr=0.1, n_iter=5000)
# Predict
def predict_logistic(X, w):
    return (sigmoid(X.dot(w)) >= 0.5).astype(int)



# Predict on test set
y_pred = predict_logistic(Xte_bias, w)
accuracy = (y_pred == yte).mean()
print("test accuracy:", accuracy)

test accuracy: 0.16666666666666666
